#!/usr/bin/env bash

set -e

echo "🚀 Installing mips-zkm-zkvm-elf..." && echo 

curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh

echo && echo "✅ Installation complete!"

