[workspace]
[package]
name = "mem-alloc-vec"
version = "0.1.0"
edition = "2021"

[dependencies]
#zkm-runtime = { git = "https://github.com/zkMIPS/zkm.git"}
##just testing
zkm-runtime = { path = "../../../zkm/runtime/entrypoint" }
