[workspace]
[package]
name = "sha2-rust"
version = "0.1.0"
edition = "2021"



[dependencies]
zkm-runtime = { git = "https://github.com/zkMIPS/zkm", branch = "main" }
sha2 = { version = "0.10.8", default-features = false }
